package com.example.tictactoe.services;

import com.example.tictactoe.game.BoardState;
import com.example.tictactoe.game.Player;

public interface GameManager {
  /*
  Board indexes
     |---|---|---|
     | 0 | 1 | 2 |
     |-----------|
     | 3 | 4 | 5 |
     |-----------|
     | 6 | 7 | 8 |
     |---|---|---|
  */

  /**
   * Update board with striker's mark on given index.
   *
   * @param sessionId Id of the game session generated by the system upon creation
   * @param striker   Player taking the turn to strike
   * @param index     Striking index on the board
   * @return Returns the updated board state
   * @throws IllegalStateException Thrown if the provided session id did not match a valid/active session.
   */
  BoardState strike(String sessionId, Player striker, int index) throws IllegalStateException;
}
